### ISSUE TITLE
Blank page when join conference

### ISSUE THREAD

**Issue by Kalimeiro** [blindsidenetworks/wordpress-plugin_bigbluebutton#11]
Hi,

when i click to join a conference, i have a blank page, refresh the page and you can enter in the conference.

in error.log :

PHP message: PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /var/www/wordpress/wp-content/plugins/bigbluebutton/php/bbb_api.php:46

an idea ? thanks.

**Comment by Kalimeiro** [comment]
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/bigbluebutton/php/bbb_api.php(46): SimpleXMLElement->__construct('<!DOCTYPE html>...')
#1 /var/www/wordpress/wp-content/plugins/bigbluebutton/php/bbb_api.php(281): bbb_wrap_simplexml_load_file('https://...')
#2 /var/www/wordpress/wp-content/plugins/bigbluebutton/bigbluebutton-plugin.php(519): BigBlueButton::createMeetingArray('User', '999999999999999...', 'NameRoom', '<br>Bienvenue d...', 'XXXXXX', 'YYYYYYY', '987987987987987...', 'https://...', 'https://www...', 'true', 0, 0, Array)
#3 /var/www/wordpress/wp-content/plugins/bigbluebutton/bigbluebutton-plugin.php(396): bigbluebutton_form('')
#4 /var/www/wordpress/wp-includes/shortcodes.php(319): bigbluebutton_shortcode('', '', 'bigbluebutton')
#5 [internal function]: do_shortcode_tag(Array)
#6 /var/www/wordpress/wp-in" while reading response header from upstream, client: 11.222.333.44, server: wordpress.fr, request: "POST /visioconference/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm-wordpress.sock:", host: "www.wordpress.fr", referrer: "https://www.wordpress.fr/visioconference/"

**Comment by Kalimeiro** [comment]
the problem has been solved by correctly specifying a pdf document :

nano /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties

set var beans.presentationService.defaultUploadedPresentation correctly. **you can't leave empty this var**.

Thanks community to not help. Thanks to not update wordpress bbb plugin, Thanks to not test you'r code correctly, blablabla...
